// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"homework-week4/internal/biz"
	"homework-week4/internal/conf"
	"homework-week4/internal/data"
	"homework-week4/internal/server"
	"homework-week4/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	libraryRepo := data.NewLibraryRepo(dataData, logger)
	libraryUseCase := biz.NewLibraryUseCase(libraryRepo, logger)
	libraryService := service.NewLibraryService(libraryUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, libraryService, logger)
	grpcServer := server.NewGRPCServer(confServer, libraryService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
